services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    network_mode: host

    # command: /bin/bash -c "apt-get install add-apt-repository -y && apt-get update && apt-get install software-properties-common -y && apt-get install python3.10 -y && python3.10 --version"
    # command: /bin/bash -c "apt-get update && apt-get install software-properties-common -y && add-apt-repository ppa:deadsnakes/ppa && apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y tzdata && apt-get install python3.10 -y && python3.10 --version"
    command: /bin/bash -c "
      apt-get update
      && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata 
      && apt-get install software-properties-common -y 
      && add-apt-repository ppa:deadsnakes/ppa -y 
      && apt-get update && apt-get install python3.10 -y 
      && python3.10 --version
      && python3.10 -m pip install pycozmo threading flask
      && python3.10 /app/explorer_robotcontroller.py"
